# Generated by Django 4.1.4 on 2022-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hf_id", models.PositiveIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("middle_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hf_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hf_id", models.PositiveIntegerField(unique=True)),
                ("position", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Close", "Close"),
                            ("Hold", "Hold"),
                            ("Resume", "Resume"),
                        ],
                        default="Close",
                        max_length=6,
                    ),
                ),
                (
                    "applicants",
                    models.ManyToManyField(
                        related_name="vacancies", to="hunt_service.applicant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicant",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="applicants", to="hunt_service.tag"
            ),
        ),
    ]
